### PR TITLE
Release v3.3.0

### PR DESCRIPTION
**Pull request by jolelievre**
Release v3.3.0:
- bug ix for 1.7.7 related to PR https://github.com/PrestaShop/PrestaShop/pull/17917

### CODE REVIEW

**Comment by Progi1984** [comment]
Thanks @jolelievre

**Comment by matks** [comment]
@Progi1984 @jolelievre Hi guys, it seems this is a v3.3.0 release but I can see the GitHub release in https://github.com/PrestaShop/ps_contactinfo/releases ?

**Comment by Progi1984** [comment]
@matks It's normal. release-drafter is not added on this repository.

**Comment by matks** [comment]
> @matks It's normal. release-drafter is not added on this repository.

If release-drafter is not active on this repository we must either add it (so it creates the GitHub release) or create the GitHub release ourselves* 😛but we cannot merge into `master` branch without doing a release

*Before we started using release-drafter, we did it manually

**Comment by Progi1984** [comment]
So manually ;)

**Pull request merged**
