### PR TITLE
Update templates to reflect changes in classic theme

### PR DESCRIPTION
**Pull request by ziegenberg**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Update templates to reflect changes in classic theme
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{no issue}.
| How to test?  | Please check in the nav, footer and the contact us page, that all detail is shown as in the classic theme.

### CODE REVIEW

**Comment by ziegenberg** [comment]
I rebased this PR onto the branch from #36, so it should be merge first.

**Comment by SimonGrn** [comment]
Hello @ziegenberg,

thanks for your PR. If I understand correctly, we need to check that all the blocks you listed (nav, footer, contact-us) are still displayed correctly, like before the modification ?

Thank you in advance.

**Comment by ziegenberg** [comment]
@SimonGrn yes, that's right. This PR updates this pluings templates to the ones used integrated in ps core.

**Comment by Progi1984** [comment]
Thanks @ziegenberg & @sarahdib

**Pull request merged**
